src/Entity/TarifaEspera.php
<?php

namespace App\Entity;

use App\Repository\TarifaEsperaRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TarifaEsperaRepository::class)]
class TarifaEspera
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $inicio_vigencia = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fin_vigencia = null;

    #[ORM\Column]
    private ?float $precio_hora = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getInicioVigencia(): ?\DateTimeInterface
    {
        return $this->inicio_vigencia;
    }

    public function setInicioVigencia(\DateTimeInterface $inicio_vigencia): static
    {
        $this->inicio_vigencia = $inicio_vigencia;

        return $this;
    }

    public function getFinVigencia(): ?\DateTimeInterface
    {
        return $this->fin_vigencia;
    }

    public function setFinVigencia(?\DateTimeInterface $fin_vigencia): static
    {
        $this->fin_vigencia = $fin_vigencia;

        return $this;
    }

    public function getPrecioHora(): ?float
    {
        return $this->precio_hora;
    }

    public function setPrecioHora(float $precio_hora): static
    {
        $this->precio_hora = $precio_hora;

        return $this;
    }

    public function getNombreTarifa(): string{
        if($this->fin_vigencia==null){
            return "Tarifa vigente";
        }
        return $this->inicio_vigencia->format("d/m/Y").' - '.$this->fin_vigencia->format("d/m/Y");
    }

}

src/Form/TarifaEsperaType.php
<?php

namespace App\Form;

use App\Entity\TarifaEspera;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TarifaEsperaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('precio_hora', null, [
                'attr' => ['class' => 'form-control'],
            ]);

        if ($options['include_inicio_vigencia']) {
            $builder->add('inicio_vigencia', null, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ]);
        }

        if ($options['include_fin_vigencia']) {
            $builder->add('fin_vigencia', null, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TarifaEspera::class,
            'include_inicio_vigencia' => true,
            'include_fin_vigencia' => false,
        ]);
    }
}

src/Controller/TarifaEsperaController.php
<?php

namespace App\Controller;

use App\Entity\TarifaEspera;
use App\Entity\Viaje;
use App\Form\TarifaEsperaType;
use App\Repository\TarifaEsperaRepository;
use App\Repository\ViajeRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/tarifa/espera')]
final class TarifaEsperaController extends AbstractController
{
    #[Route(name: 'app_tarifa_espera_index', methods: ['GET'])]
    public function index(TarifaEsperaRepository $tarifaEsperaRepository): Response
    {
        return $this->render('tarifa_espera/index.html.twig', [
            'tarifa_esperas' => $tarifaEsperaRepository->findAllByInicioVigencia(),
        ]);
    }

    #[Route('/actual', name: 'app_tarifa_espera_actual', methods: ['GET'])]
    public function verActual(Request $request, TarifaEsperaRepository $tarifaEsperaRepository, EntityManagerInterface $manager): Response
    {
        $tarifaEsperaActual=$tarifaEsperaRepository->findTarifaEsperaActual();
        if($tarifaEsperaActual){
            return $this->show($tarifaEsperaActual, $manager, true);
        }

        return $this->redirectToRoute('app_tarifa_espera_new');
    }

    #[Route('/new', name: 'app_tarifa_espera_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $tarifaEspera = new TarifaEspera();
        $form = $this->createForm(TarifaEsperaType::class, $tarifaEspera);
        $form->handleRequest($request);

        $tarifaEsperaRepository=$entityManager->getRepository(TarifaEspera::class);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($request->get('id_tarifa_actual')) {
                $tarifaAnterior = $tarifaEsperaRepository->findOneBy(['id' => $request->get('id_tarifa_actual')]);
                $fechaFinalizacion=DateTime::createFromInterface($tarifaEspera->getInicioVigencia());
                $fechaFinalizacion->sub(new \DateInterval('P1D'));
                $tarifaAnterior->setFinVigencia($fechaFinalizacion);
                $entityManager->persist($tarifaAnterior);
            }

            $entityManager->persist($tarifaEspera);
            $entityManager->flush();

            return $this->redirectToRoute('app_tarifa_espera_index', [], Response::HTTP_SEE_OTHER);
        }

        $tarifaActual=$tarifaEsperaRepository->findTarifaEsperaActual();

        return $this->render('tarifa_espera/new.html.twig', [
            'tarifa_espera' => $tarifaEspera,
            'form' => $form,
            'tarifa_actual'=>$tarifaActual,
        ]);
    }

    #[Route('/{id}', name: 'app_tarifa_espera_show', methods: ['GET'])]
    public function show(TarifaEspera $tarifaEspera, EntityManagerInterface $manager, $incrustada=false): Response
    {
        $viajesRepository=$manager->getRepository(Viaje::class);

        /** @var Viaje[] $viajes */
        $viajes=$viajesRepository->findByTarifaEsperaField($tarifaEspera->getId());
        return $this->render('tarifa_espera/show.html.twig', [
            'tarifa_espera' => $tarifaEspera,
            'viajes' => $viajes,
            'incrustada' => $incrustada,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tarifa_espera_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, TarifaEspera $tarifaEspera, EntityManagerInterface $entityManager, $incrustada=false): Response
    {
        $form = $this->createForm(TarifaEsperaType::class, $tarifaEspera, ['include_inicio_vigencia'=>false]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_tarifa_espera_index', [], Response::HTTP_SEE_OTHER);
        }

        $viajesRepository=$entityManager->getRepository(Viaje::class);

        /** @var Viaje[] $viajes */
        $viajes=$viajesRepository->findByTarifaEsperaField($tarifaEspera->getId());

        return $this->render('tarifa_espera/edit.html.twig', [
            'tarifa_espera' => $tarifaEspera,
            'form' => $form,
            'viajes' => $viajes,
            'incrustada' => $incrustada,
        ]);
    }

    #[Route('/{id}', name: 'app_tarifa_espera_delete', methods: ['POST'])]
    public function delete(Request $request, TarifaEspera $tarifaEspera, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tarifaEspera->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($tarifaEspera);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tarifa_espera_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tarifa_espera/_delete_form.html.twig
<form method="post" action="{{ path('app_tarifa_espera_delete', {'id': tarifa_espera.id}) }}" onsubmit="return confirm('{{ confirmar_borrado_tarifa_espera }}');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tarifa_espera.id) }}">
    <button class="{{ estilo_boton_eliminar }}">{{ eliminar }}</button>
</form>

templates/tarifa_espera/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="{{ estilo_boton_guardar }}">{{ button_label|default(guardar) }}</button>
    {% if tarifa_actual|default %}
        <input type="hidden" name="id_tarifa_actual" value="{{ tarifa_actual.id }}">
    {% endif %}
{{ form_end(form) }}

templates/tarifa_espera/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_editar_tarifa_espera }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_editar_tarifa_espera }}</h3>
{% endblock %}

{% block contenido %}
    {{ include('tarifa_espera/_form.html.twig', {'button_label': actualizar}) }}

    <h5>{{ navega_modifica_viajes_con_esta_tarifa }}</h5>
    <div class="{{ estilo_subcontenido }}">
        {{ include('viaje/_tabla_viajes.html.twig') }}
    </div>

{% endblock %}

{% block acciones %}
    <a href="{{ path('app_tarifa_espera_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>

    {# No se puede eliminar una tarifa
        {% if not viajes %}
            {{ include('tarifa_espera/_delete_form.html.twig') }}
        {% endif %}
    #}
{% endblock %}

templates/tarifa_espera/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_listado_tarifa_espera }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_listado_tarifa_espera }}</h3>
{% endblock %}

{% block contenido %}
    <table class="{{ estilo_tabla }}">
        <thead>
            <tr>
                <th>{{ etiqueta_inicio_vigencia }}</th>
                <th>{{ etiqueta_fin_vigencia }}</th>
                <th>{{ etiqueta_precio_hora }}</th>
                <th>{{ etiqueta_acciones }}</th>
            </tr>
        </thead>
        <tbody>
        {% for tarifa_espera in tarifa_esperas %}
            <tr>
                <td>{{ tarifa_espera.inicioVigencia ? tarifa_espera.inicioVigencia|date('Y-m-d') : '' }}</td>
                <td>{{ tarifa_espera.finVigencia ? tarifa_espera.finVigencia|date('Y-m-d') : '' }}</td>
                <td>{{ tarifa_espera.precioHora }}</td>
                <td>
                    <a href="{{ path('app_tarifa_espera_show', {'id': tarifa_espera.id}) }}" class="{{ estilo_boton_detalle_incrustado }}">{{ ver_detalle }}</a>
                    <a href="{{ path('app_tarifa_espera_edit', {'id': tarifa_espera.id}) }}" class="{{ estilo_boton_editar_incrustado }}">{{ editar }}</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">{{ sin_resultados }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_tarifa_espera_new') }}" class="{{ estilo_boton_nuevo_elemento }}">{{ navega_nueva_tarifa_espera }}</a>
{% endblock %}

templates/tarifa_espera/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_nueva_tarifa_espera }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_nueva_tarifa_espera }}</h3>
{% endblock %}

{% block contenido %}
    {% for msg in app.flashes('error') %}
        <div class="alert alert-danger">{{ msg }}</div>
    {% endfor %}
    {{ include('tarifa_espera/_form.html.twig') }}

    {% if(not tarifa_actual|default) %}
        <h5>{{ etiqueta_tarifa_no_definida }}</h5>
    {% else %}
        <h5>{{ etiqueta_tarifa_espera_actual }}</h5>
        <table class="{{ estilo_tabla }}">
            <tbody>
            <tr>
                <th>{{ etiqueta_inicio_vigencia }}</th>
                <td>{{ tarifa_actual.inicioVigencia|date('d-m-Y') }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_precio_hora }}</th>
                <td>{{ tarifa_actual.precioHora }}</td>
            </tr>
            </tbody>
        </table>
    {% endif %}
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_tarifa_espera_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>
{% endblock %}

templates/tarifa_espera/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_detalle_tarifa_espera }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_detalle_tarifa_espera }}</h3>
{% endblock %}

{% block contenido %}
    <table class="{{ estilo_tabla }}">
        <tbody>
            <tr>
                <th>{{ etiqueta_inicio_vigencia }}</th>
                <td>{{ tarifa_espera.inicioVigencia ? tarifa_espera.inicioVigencia|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_fin_vigencia }}</th>
                <td>{{ tarifa_espera.finVigencia ? tarifa_espera.finVigencia|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_precio_hora }}</th>
                <td>{{ tarifa_espera.precioHora }}</td>
            </tr>
        </tbody>
    </table>

    <h5>{{ navega_viajes_con_esta_tarifa }}</h5>
    <div class="{{ estilo_subcontenido }}">
        {{ include('viaje/_tabla_viajes.html.twig') }}
    </div>
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_tarifa_espera_index') }}" class="{{ estilo_boton_volver }}">{{ navega_ver_historico_tarifas_espera }}</a>

    <a href="{{ path('app_tarifa_espera_edit', {'id': tarifa_espera.id}) }}" class="{{ estilo_boton_editar }}">{{ editar }}</a>

    <a href="{{ path('app_tarifa_espera_new') }}" class="{{ estilo_boton_nuevo_elemento }}">{{ navega_nueva_tarifa_espera }}</a>

    {# No se contempla la opción de eliminar tarifas
    {% if not viajes %}
        {{ include('tarifa_espera/_delete_form.html.twig') }}
    {% endif %}
    #}
{% endblock %}