src/Entity/Paciente.php
<?php

namespace App\Entity;

use App\Repository\PacienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PacienteRepository::class)]
class Paciente
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    private ?string $nombre = null;

    #[ORM\Column(length: 40)]
    private ?string $apellido1 = null;

    #[ORM\Column(length: 40, nullable: true)]
    private ?string $apellido2 = null;

    #[ORM\Column(length: 40, nullable: true)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $telefono = null;

    #[ORM\Column(nullable: true)]
    private ?int $telefono2 = null;

    #[ORM\Column(length: 12)]
    private ?string $dni = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Localidad $id_localidad = null;

    #[ORM\Column]
    private ?bool $es_socio = null;

    #[ORM\Column(length: 10)]
    private ?string $codigo = null;

    /**
     * @var Collection<int, Viaje>
     */
    #[ORM\OneToMany(targetEntity: Viaje::class, mappedBy: 'id_paciente')]
    private Collection $viajes;

    public function __construct()
    {
        $this->viajes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido1(): ?string
    {
        return $this->apellido1;
    }

    public function setApellido1(string $apellido1): static
    {
        $this->apellido1 = $apellido1;

        return $this;
    }

    public function getApellido2(): ?string
    {
        return $this->apellido2;
    }

    public function setApellido2(?string $apellido2): static
    {
        $this->apellido2 = $apellido2;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(int $telefono): static
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getTelefono2(): ?int
    {
        return $this->telefono2;
    }

    public function setTelefono2(?int $telefono2): static
    {
        $this->telefono2 = $telefono2;

        return $this;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(string $dni): static
    {
        $this->dni = $dni;

        return $this;
    }

    public function getIdLocalidad(): ?Localidad
    {
        return $this->id_localidad;
    }

    public function setIdLocalidad(?Localidad $id_localidad): static
    {
        $this->id_localidad = $id_localidad;

        return $this;
    }

    public function isEsSocio(): ?bool
    {
        return $this->es_socio;
    }

    public function setEsSocio(bool $es_socio): static
    {
        $this->es_socio = $es_socio;

        return $this;
    }

    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    public function setCodigo(string $codigo): static
    {
        $this->codigo = $codigo;

        return $this;
    }

    /**
     * @return Collection<int, Viaje>
     */
    public function getViajes(): Collection
    {
        return $this->viajes;
    }

    public function addViaje(Viaje $viaje): static
    {
        if (!$this->viajes->contains($viaje)) {
            $this->viajes->add($viaje);
            $viaje->setIdPaciente($this);
        }

        return $this;
    }

    public function removeViaje(Viaje $viaje): static
    {
        if ($this->viajes->removeElement($viaje)) {
            // set the owning side to null (unless already changed)
            if ($viaje->getIdPaciente() === $this) {
                $viaje->setIdPaciente(null);
            }
        }

        return $this;
    }

    public function generarCodigo(){
        $this->codigo = bin2hex(random_bytes(4));
    }

    public function getNombreCompleto(): string{
        return $this->nombre . ' ' . $this->apellido1.(($this->apellido2)?' '.$this->apellido2:'');
    }
}

src/Form/PacienteType.php
<?php

namespace App\Form;

use App\Entity\Localidad;
use App\Entity\Paciente;
use App\Utils\Globales;
use phpDocumentor\Reflection\Types\String_;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PacienteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre', null, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('apellido1', null, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('apellido2', null, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('email', null, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('telefono', null, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('telefono2', null, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('dni', null, [
                'attr' => ['class' => 'form-control'],
                'label' => Globales::getGlobales()['etiqueta_dni'],
            ])
            ->add('es_socio', CheckboxType::class, [
                'required' => false,
                'attr' => ['class' => 'form-check-label'],
            ])
            ->add('id_localidad', EntityType::class, [
                'class' => Localidad::class,
                'choice_label' => 'nombre',
                'attr' => ['class' => 'form-select'],
                'label' => Globales::getGlobales()['etiqueta_localidad_paciente'],
            ])
        ;

        if ($options['include_codigo']) {
            $builder->add('codigo', null, [
                'attr' => ['class' => 'form-control'],
            ]);
        }

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Paciente::class,
            'include_codigo' => true,
        ]);
    }
}

src/Controller/PacienteController.php
<?php

namespace App\Controller;

use App\Entity\Localidad;
use App\Entity\Paciente;
use App\Entity\Viaje;
use App\Form\LocalidadType;
use App\Form\PacienteType;
use App\Repository\LocalidadRepository;
use App\Repository\PacienteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/paciente')]
final class PacienteController extends AbstractController
{
    #[Route(name: 'app_paciente_index', methods: ['GET'])]
    public function index(PacienteRepository $pacienteRepository): Response
    {
        return $this->render('paciente/index.html.twig', [
            'pacientes' => $pacienteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_paciente_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        if(!$entityManager->getRepository(Localidad::class)->count()){
            $this->addFlash('error', 'Antes de crear un paciente es necesario que exista, como mínimo, una localidad.');
            return $this->redirectToRoute('app_localidad_new');
        }

        $paciente = new Paciente();
        $form = $this->createForm(PacienteType::class, $paciente, ['include_codigo'=>false]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $paciente->generarCodigo();
            $entityManager->persist($paciente);
            $entityManager->flush();

            return $this->redirectToRoute('app_paciente_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('paciente/new.html.twig', [
            'paciente' => $paciente,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_paciente_show', methods: ['GET'])]
    public function show(Paciente $paciente): Response
    {
        return $this->render('paciente/show.html.twig', [
            'paciente' => $paciente,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_paciente_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Paciente $paciente, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PacienteType::class, $paciente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_paciente_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('paciente/edit.html.twig', [
            'paciente' => $paciente,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_paciente_delete', methods: ['POST'])]
    public function delete(Request $request, Paciente $paciente, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$paciente->getId(), $request->getPayload()->getString('_token'))) {
            $numViajes=$entityManager->getRepository(Viaje::class)->getNumViajesByPaciente($paciente->getId());
            if($numViajes>0){
                $this->addFlash('error', 'El paciente '.$paciente->getNombreCompleto().' no puede ser eliminado porque tiene '.$numViajes.' viajes asociados.');
                return $this->redirectToRoute('app_main_menu', [], Response::HTTP_SEE_OTHER);
            }

            $entityManager->remove($paciente);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_paciente_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/paciente/_delete_form.html.twig
<form method="post" action="{{ path('app_paciente_delete', {'id': paciente.id}) }}" onsubmit="return confirm('{{ confirmar_borrado_paciente }}');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ paciente.id) }}">
    <button class="{{ estilo_boton_eliminar }}">{{ eliminar }}</button>
</form>

templates/paciente/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="{{ estilo_boton_guardar }}">{{ button_label|default(guardar) }}</button>
{{ form_end(form) }}

templates/paciente/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_editar_paciente }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_editar_paciente }}</h3>
{% endblock %}

{% block contenido %}
    {{ include('paciente/_form.html.twig', {'button_label': actualizar}) }}
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_paciente_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>

    {{ include('paciente/_delete_form.html.twig') }}
{% endblock %}

templates/paciente/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_listado_pacientes }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_listado_pacientes }}</h3>
{% endblock %}

{% block contenido %}
    <table class="{{ estilo_tabla }}">
        <thead>
            <tr>
                <th>{{ etiqueta_nombre_completo_paciente }}</th>
                <th>{{ etiqueta_email }}</th>
                <th>{{ etiqueta_telefono1 }}</th>
                <th>{{ etiqueta_localidad_paciente }}</th>
                <th>{{ etiqueta_dni }}</th>
                <th>{{ etiqueta_es_socio }}</th>
                <th>{{ etiqueta_codigo_paciente }}</th>
                <th>{{ etiqueta_acciones }}</th>
            </tr>
        </thead>
        <tbody>
        {% for paciente in pacientes %}
            <tr>
                <td>{{ paciente.nombre }} {{ paciente.apellido1 }} {{ paciente.apellido2 }}</td>
                <td>{{ paciente.email }}</td>
                <td>{{ paciente.telefono }}</td>
                <td>{{ paciente.idLocalidad.nombre }}</td>
                <td>{{ paciente.dni }}</td>
                <td>{{ paciente.esSocio ? booleano_si : booleano_no }}</td>
                <td>{{ paciente.codigo }}</td>
                <td>
                    <a href="{{ path('app_paciente_show', {'id': paciente.id}) }}" class="{{ estilo_boton_detalle_incrustado }}">{{ ver_detalle }}</a>
                    <a href="{{ path('app_paciente_edit', {'id': paciente.id}) }}" class="{{ estilo_boton_editar_incrustado }}">{{ editar }}</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">{{ sin_resultados }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_paciente_new') }}" class="{{ estilo_boton_nuevo_elemento }}">{{ navega_nuevo_paciente }}</a>
{% endblock %}

templates/paciente/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_nuevo_paciente }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_nuevo_paciente }}</h3>
{% endblock %}

{% block contenido %}
    {% for msg in app.flashes('error') %}
        <div class="alert alert-danger">{{ msg }}</div>
    {% endfor %}
    {{ include('paciente/_form.html.twig') }}
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_paciente_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>
{% endblock %}

templates/paciente/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_detalle_paciente }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_detalle_paciente }}</h3>
{% endblock %}

{% block contenido %}
    <table class="{{ estilo_tabla }}">
        <tbody>
            <tr>
                <th>{{ etiqueta_nombre }}</th>
                <td>{{ paciente.nombre }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_apellido1 }}</th>
                <td>{{ paciente.apellido1 }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_apellido2 }}</th>
                <td>{{ paciente.apellido2 }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_nombre_localidad }}</th>
                <td>{{ paciente.idLocalidad.nombre }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_email }}</th>
                <td>{{ paciente.email }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_telefono1 }}</th>
                <td>{{ paciente.telefono }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_telefono2 }}</th>
                <td>{{ paciente.telefono2 }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_dni }}</th>
                <td>{{ paciente.dni }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_es_socio }}</th>
                <td>{{ paciente.esSocio ? booleano_si : booleano_no }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_codigo_paciente }}</th>
                <td>{{ paciente.codigo }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_paciente_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>

    <a href="{{ path('app_paciente_edit', {'id': paciente.id}) }}" class="{{ estilo_boton_editar }}">{{ editar }}</a>

    {{ include('paciente/_delete_form.html.twig') }}
{% endblock %}