src/Entity/Paciente.php
<?php

namespace App\Entity;

use App\Repository\PacienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PacienteRepository::class)]
class Paciente
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    private ?string $nombre = null;

    #[ORM\Column(length: 40)]
    private ?string $apellido1 = null;

    #[ORM\Column(length: 40, nullable: true)]
    private ?string $apellido2 = null;

    #[ORM\Column(length: 40, nullable: true)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $telefono = null;

    #[ORM\Column(nullable: true)]
    private ?int $telefono2 = null;

    #[ORM\Column(length: 12)]
    private ?string $dni = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Localidad $id_localidad = null;

    #[ORM\Column]
    private ?bool $es_socio = null;

    #[ORM\Column(length: 10)]
    private ?string $codigo = null;

    /**
     * @var Collection<int, Viaje>
     */
    #[ORM\OneToMany(targetEntity: Viaje::class, mappedBy: 'id_paciente')]
    private Collection $viajes;

    public function __construct()
    {
        $this->viajes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido1(): ?string
    {
        return $this->apellido1;
    }

    public function setApellido1(string $apellido1): static
    {
        $this->apellido1 = $apellido1;

        return $this;
    }

    public function getApellido2(): ?string
    {
        return $this->apellido2;
    }

    public function setApellido2(?string $apellido2): static
    {
        $this->apellido2 = $apellido2;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(int $telefono): static
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getTelefono2(): ?int
    {
        return $this->telefono2;
    }

    public function setTelefono2(?int $telefono2): static
    {
        $this->telefono2 = $telefono2;

        return $this;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(string $dni): static
    {
        $this->dni = $dni;

        return $this;
    }

    public function getIdLocalidad(): ?Localidad
    {
        return $this->id_localidad;
    }

    public function setIdLocalidad(?Localidad $id_localidad): static
    {
        $this->id_localidad = $id_localidad;

        return $this;
    }

    public function isEsSocio(): ?bool
    {
        return $this->es_socio;
    }

    public function setEsSocio(bool $es_socio): static
    {
        $this->es_socio = $es_socio;

        return $this;
    }

    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    public function setCodigo(string $codigo): static
    {
        $this->codigo = $codigo;

        return $this;
    }

    /**
     * @return Collection<int, Viaje>
     */
    public function getViajes(): Collection
    {
        return $this->viajes;
    }

    public function addViaje(Viaje $viaje): static
    {
        if (!$this->viajes->contains($viaje)) {
            $this->viajes->add($viaje);
            $viaje->setIdPaciente($this);
        }

        return $this;
    }

    public function removeViaje(Viaje $viaje): static
    {
        if ($this->viajes->removeElement($viaje)) {
            // set the owning side to null (unless already changed)
            if ($viaje->getIdPaciente() === $this) {
                $viaje->setIdPaciente(null);
            }
        }

        return $this;
    }

    public function generarCodigo(){
        $this->codigo = bin2hex(random_bytes(4));
    }

    public function getNombreCompleto(): string{
        return $this->nombre . ' ' . $this->apellido1.(($this->apellido2)?' '.$this->apellido2:'');
    }
}

src/Entity/Viaje.php
<?php

namespace App\Entity;

use App\Repository\ViajeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ViajeRepository::class)]
class Viaje
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha = null;

    #[ORM\Column]
    private ?bool $es_ida_vuelta = null;

    #[ORM\Column(enumType: Valoracion::class)]
    private ?Valoracion $valoracion = null;

    #[ORM\Column(length: 600, nullable: true)]
    private ?string $comentarios = null;

    #[ORM\ManyToOne(inversedBy: 'viajes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Paciente $id_paciente = null;

    #[ORM\ManyToOne(inversedBy: 'viajes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Conductor $id_conductor = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?TarifaKm $id_tarifa_km = null;

    #[ORM\ManyToOne]
    private ?TarifaEspera $id_tarifa_espera = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Localidad $id_localidad = null;

    #[ORM\Column]
    private ?float $num_kilometros = null;

    #[ORM\Column]
    private ?float $importe_distancia = null;

    #[ORM\Column(nullable: true)]
    private ?float $horas_espera = null;

    #[ORM\Column(nullable: true)]
    private ?float $importe_espera = null;

    #[ORM\Column]
    private ?float $importe_total = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): static
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function isEsIdaVuelta(): ?bool
    {
        return $this->es_ida_vuelta;
    }

    public function setEsIdaVuelta(bool $es_ida_vuelta): static
    {
        $this->es_ida_vuelta = $es_ida_vuelta;

        return $this;
    }

    public function getValoracion(): ?Valoracion
    {
        return $this->valoracion;
    }

    public function setValoracion(Valoracion $valoracion): static
    {
        $this->valoracion = $valoracion;

        return $this;
    }

    public function getComentarios(): ?string
    {
        return $this->comentarios;
    }

    public function setComentarios(?string $comentarios): static
    {
        $this->comentarios = $comentarios;

        return $this;
    }

    public function getIdPaciente(): ?Paciente
    {
        return $this->id_paciente;
    }

    public function setIdPaciente(?Paciente $id_paciente): static
    {
        $this->id_paciente = $id_paciente;

        return $this;
    }

    public function getIdConductor(): ?Conductor
    {
        return $this->id_conductor;
    }

    public function setIdConductor(?Conductor $id_conductor): static
    {
        $this->id_conductor = $id_conductor;

        return $this;
    }

    public function getIdTarifaKm(): ?TarifaKm
    {
        return $this->id_tarifa_km;
    }

    public function setIdTarifaKm(?TarifaKm $id_tarifa_km): static
    {
        $this->id_tarifa_km = $id_tarifa_km;

        return $this;
    }

    public function getIdTarifaEspera(): ?TarifaEspera
    {
        return $this->id_tarifa_espera;
    }

    public function setIdTarifaEspera(?TarifaEspera $id_tarifa_espera): static
    {
        $this->id_tarifa_espera = $id_tarifa_espera;

        return $this;
    }

    public function getIdLocalidad(): ?Localidad
    {
        return $this->id_localidad;
    }

    public function setIdLocalidad(?Localidad $id_localidad): static
    {
        $this->id_localidad = $id_localidad;

        return $this;
    }

    public function getNumKilometros(): ?float
    {
        return $this->num_kilometros;
    }

    public function setNumKilometros(float $num_kilometros): static
    {
        $this->num_kilometros = $num_kilometros;

        return $this;
    }

    public function getImporteDistancia(): ?float
    {
        return $this->importe_distancia;
    }

    public function setImporteDistancia(float $importe_distancia): static
    {
        $this->importe_distancia = $importe_distancia;

        return $this;
    }

    public function getHorasEspera(): ?float
    {
        return $this->horas_espera;
    }

    public function setHorasEspera(?float $horas_espera): static
    {
        $this->horas_espera = $horas_espera;

        return $this;
    }

    public function getImporteEspera(): ?float
    {
        return $this->importe_espera;
    }

    public function setImporteEspera(?float $importe_espera): static
    {
        $this->importe_espera = $importe_espera;

        return $this;
    }

    public function getImporteTotal(): ?float
    {
        return $this->importe_total;
    }

    public function setImporteTotal(float $importe_total): static
    {
        $this->importe_total = $importe_total;

        return $this;
    }
}

src/Controller/ViajeController.php
<?php

namespace App\Controller;

use App\Entity\Conductor;
use App\Entity\Localidad;
use App\Entity\Paciente;
use App\Entity\TarifaEspera;
use App\Entity\TarifaKm;
use App\Entity\Viaje;
use App\Form\ViajeType;
use App\Repository\ViajeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/viaje')]
final class ViajeController extends AbstractController
{
    #[Route(name: 'app_viaje_index', methods: ['GET'])]
    public function index(ViajeRepository $viajeRepository): Response
    {
        return $this->render('viaje/index.html.twig', [
            'viajes' => $viajeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_viaje_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

        $tarifasEsperaRepository=$entityManager->getRepository(TarifaEspera::class);
        $tarifasKmRepository=$entityManager->getRepository(TarifaKm::class);

        $valoresTarifasEspera=$tarifasEsperaRepository->getJsonValues();
        $valoresTarifasKm=$tarifasKmRepository->getJsonValues();

        if(!$valoresTarifasEspera) {
            $this->addFlash('error', 'Antes de crear un viaje es necesario que exista una tarifa de espera.');
            return $this->redirectToRoute('app_tarifa_espera_new');
        } elseif (!$valoresTarifasKm) {
            $this->addFlash('error', 'Antes de crear un viaje es necesario que exista una tarifa por kilómetros.');
            return $this->redirectToRoute('app_tarifa_km_new');
        } elseif(!$entityManager->getRepository(Localidad::class)->count()){
            $this->addFlash('error', 'Antes de crear un paciente es necesario que exista, como mínimo, una localidad.');
            return $this->redirectToRoute('app_localidad_new');
        } elseif(!$entityManager->getRepository(Paciente::class)->count()){
            $this->addFlash('error', 'Antes de crear un viaje es necesario que exista, como mínimo, un paciente.');
            return $this->redirectToRoute('app_paciente_new');
        } elseif(!$entityManager->getRepository(Conductor::class)->count()){
            $this->addFlash('error', 'Antes de crear un viaje es necesario que exista, como mínimo, un conductor.');
            return $this->redirectToRoute('app_conductor_new');
        }

        $tarifaEsperaActual=$tarifasEsperaRepository->findTarifaEsperaActual();
        $tarifaKmActual=$tarifasKmRepository->findTarifaKmActual();

        $viaje = new Viaje();
        $viaje->setIdTarifaEspera($tarifaEsperaActual);
        $viaje->setIdTarifaKm($tarifaKmActual);

        $form = $this->createForm(ViajeType::class, $viaje);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $viaje->setImporteEspera(($viaje->getHorasEspera()?$viaje->getHorasEspera():0)*$viaje->getIdTarifaEspera()->getPrecioHora());
            $viaje->setImporteDistancia($viaje->getNumKilometros()*$viaje->getIdTarifaKm()->getPrecioKm());
            $viaje->setImporteTotal($viaje->getImporteDistancia()+$viaje->getImporteEspera());
            $viaje->setIdLocalidad($viaje->getIdPaciente()->getIdLocalidad());

            $entityManager->persist($viaje);
            $entityManager->flush();

            return $this->redirectToRoute('app_viaje_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('viaje/new.html.twig', [
            'viaje' => $viaje,
            'form' => $form,
            'valoresTarifasEspera'=>$valoresTarifasEspera,
            'valoresTarifasKm'=>$valoresTarifasKm,
        ]);
    }

    #[Route('/{id}', name: 'app_viaje_show', methods: ['GET'])]
    public function show(Viaje $viaje): Response
    {
        return $this->render('viaje/show.html.twig', [
            'viaje' => $viaje,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_viaje_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Viaje $viaje, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ViajeType::class, $viaje);
        $form->handleRequest($request);

        $tarifasEsperaRepository=$entityManager->getRepository(TarifaEspera::class);
        $tarifasKmRepository=$entityManager->getRepository(TarifaKm::class);

        $valoresTarifasEspera=$tarifasEsperaRepository->getJsonValues();
        $valoresTarifasKm=$tarifasKmRepository->getJsonValues();

        if ($form->isSubmitted() && $form->isValid()) {
            $viaje->setImporteEspera(($viaje->getHorasEspera()?$viaje->getHorasEspera():0)*$viaje->getIdTarifaEspera()->getPrecioHora());
            $viaje->setImporteDistancia($viaje->getNumKilometros()*$viaje->getIdTarifaKm()->getPrecioKm());
            $viaje->setImporteTotal($viaje->getImporteDistancia()+$viaje->getImporteEspera());
            $viaje->setIdLocalidad($viaje->getIdPaciente()->getIdLocalidad());

            $entityManager->flush();

            return $this->redirectToRoute('app_viaje_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('viaje/edit.html.twig', [
            'viaje' => $viaje,
            'form' => $form,
            'valoresTarifasEspera'=>$valoresTarifasEspera,
            'valoresTarifasKm'=>$valoresTarifasKm,
        ]);
    }

    #[Route('/{id}', name: 'app_viaje_delete', methods: ['POST'])]
    public function delete(Request $request, Viaje $viaje, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$viaje->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($viaje);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_viaje_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/viaje/_delete_form.html.twig
<form method="post" action="{{ path('app_viaje_delete', {'id': viaje.id}) }}" onsubmit="return confirm('{{ confirmar_borrado_viaje }}');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ viaje.id) }}">
    <button class="{{ estilo_boton_eliminar }}">{{ eliminar }}</button>
</form>

templates/viaje/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {% if(valoresTarifasEspera|default) %}
        <input type="hidden" id="tarifas_espera" value="{{ valoresTarifasEspera }}">
        <input type="hidden" id="tarifas_km" value="{{ valoresTarifasKm }}">
    {% endif %}
    <label for="total">Importe total</label>
    <input type="text" id="total" value="0" disabled/>
    <br>
    <button class="{{ estilo_boton_guardar }}">{{ button_label|default(guardar) }}</button>
{{ form_end(form) }}

templates/viaje/_tabla_viajes.html.twig
{% set numCols=7 %}
<table class="{{ estilo_tabla }}">
    <thead>
    <tr>
        <th>{{ etiqueta_fecha }}</th>
        <th>{{ etiqueta_nombre_completo_paciente }}</th>
        <th>{{ etiqueta_valoracion_viaje }}</th>
        <th>{{ etiqueta_comentarios_viaje }}</th>
        <th>{{ etiqueta_destino }}</th>
        <th>{{ etiqueta_kilometros }}</th>
        <th>{{ etiqueta_importe_total }}</th>
        {% if not incrustada|default %}
            {% set numCols=numCols+1 %}
            <th>{{ etiqueta_acciones }}</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for viaje in viajes %}
        <tr>
            <td>{{ viaje.fecha ? viaje.fecha|date('d-m-Y') : '' }}</td>
            <td>{{ viaje.idPaciente.nombreCompleto }}</td>
            <td>{{ viaje.valoracion.value }}</td>
            <td>{{ viaje.comentarios|trim ? '...':'Sin comentarios' }}</td>
            <td>{{ viaje.idLocalidad.nombre }}</td>
            <td>{{ viaje.numKilometros }}</td>
            <td>{{ viaje.importeTotal }}</td>
            {% if not incrustada|default %}
                <td>
                    <a href="{{ path('app_viaje_show', {'id': viaje.id}) }}" class="{{ estilo_boton_detalle_incrustado }}">{{ ver_detalle }}</a>
                    <a href="{{ path('app_viaje_edit', {'id': viaje.id}) }}" class="{{ estilo_boton_editar_incrustado }}">{{ editar }}</a>
                </td>
            {% endif %}
        </tr>
    {% else %}
        <tr>
            <td colspan="{{ numCols }}">{{ sin_resultados }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/viaje/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_editar_viaje }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_editar_viaje }}</h3>
{% endblock %}

{% block contenido %}
    {{ include('viaje/_form.html.twig', {'button_label': actualizar}) }}
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_viaje_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>

    {{ include('viaje/_delete_form.html.twig') }}
{% endblock %}

templates/viaje/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_listado_viajes }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_listado_viajes }}</h3>
{% endblock %}

{% block contenido %}
    {% include('viaje/_tabla_viajes.html.twig') %}
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_viaje_new') }}" class="{{ estilo_boton_nuevo_elemento }}">{{ navega_nuevo_viaje }}</a>
{% endblock %}

templates/viaje/new.html.twig
{% extends 'layout.html.twig' %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block title %}{{ navega_nuevo_viaje }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_nuevo_viaje }}</h3>
{% endblock %}

{% block contenido %}
    {{ include('viaje/_form.html.twig') }}
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_viaje_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>
{% endblock %}

templates/viaje/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_detalle_viaje }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_detalle_viaje }}</h3>

{% endblock %}

{% block contenido %}

    <table class="{{ estilo_tabla }}">
        <tbody>
        <tr>
            <th>{{ etiqueta_fecha }}</th>
            <td>{{ viaje.fecha ? viaje.fecha|date('d-m-Y') : '' }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_es_ida_y_vuelta }}</th>
            <td>{{ viaje.esIdaVuelta ? booleano_si : booleano_no }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_valoracion_viaje }}</th>
            <td>{{ viaje.valoracion.value }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_comentarios_viaje }}</th>
            <td>{{ viaje.comentarios }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_kilometros }}</th>
            <td>{{ viaje.numKilometros }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_importe_kilometros }}</th>
            <td>{{ viaje.importeDistancia }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_espera }}</th>
            <td>{{ viaje.horasEspera }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_importe_espera }}</th>
            <td>{{ viaje.importeEspera }}</td>
        </tr>
        <tr>
            <th>{{ etiqueta_importe_total }}</th>
            <td>{{ viaje.importeTotal }}</td>
        </tr>
        </tbody>
    </table>


{% endblock %}

{% block acciones %}

    <a href="{{ path('app_viaje_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>

    <a href="{{ path('app_viaje_edit', {'id': viaje.id}) }}" class="{{ estilo_boton_editar }}">{{ editar }}</a>

    {{ include('viaje/_delete_form.html.twig') }}
{% endblock %}