src/Entity/Conductor.php
<?php

namespace App\Entity;

use App\Repository\ConductorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConductorRepository::class)]
class Conductor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    private ?string $nombre = null;

    #[ORM\Column(length: 40)]
    private ?string $apellido1 = null;

    #[ORM\Column(length: 40, nullable: true)]
    private ?string $apellido2 = null;

    #[ORM\Column(length: 12)]
    private ?string $nif = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_alta = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_baja = null;

    /**
     * @var Collection<int, Viaje>
     */
    #[ORM\OneToMany(targetEntity: Viaje::class, mappedBy: 'id_conductor')]
    private Collection $viajes;

    public function __construct()
    {
        $this->viajes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido1(): ?string
    {
        return $this->apellido1;
    }

    public function setApellido1(string $apellido1): static
    {
        $this->apellido1 = $apellido1;

        return $this;
    }

    public function getApellido2(): ?string
    {
        return $this->apellido2;
    }

    public function setApellido2(?string $apellido2): static
    {
        $this->apellido2 = $apellido2;

        return $this;
    }

    public function getNif(): ?string
    {
        return $this->nif;
    }

    public function setNif(string $nif): static
    {
        $this->nif = $nif;

        return $this;
    }

    public function getFechaAlta(): ?\DateTimeInterface
    {
        return $this->fecha_alta;
    }

    public function setFechaAlta(\DateTimeInterface $fecha_alta): static
    {
        $this->fecha_alta = $fecha_alta;

        return $this;
    }

    public function getFechaBaja(): ?\DateTimeInterface
    {
        return $this->fecha_baja;
    }

    public function setFechaBaja(?\DateTimeInterface $fecha_baja): static
    {
        $this->fecha_baja = $fecha_baja;

        return $this;
    }

    /**
     * @return Collection<int, Viaje>
     */
    public function getViajes(): Collection
    {
        return $this->viajes;
    }

    public function addViaje(Viaje $viaje): static
    {
        if (!$this->viajes->contains($viaje)) {
            $this->viajes->add($viaje);
            $viaje->setIdConductor($this);
        }

        return $this;
    }

    public function removeViaje(Viaje $viaje): static
    {
        if ($this->viajes->removeElement($viaje)) {
            // set the owning side to null (unless already changed)
            if ($viaje->getIdConductor() === $this) {
                $viaje->setIdConductor(null);
            }
        }

        return $this;
    }

    public function getNombreCompleto(): string{
        return $this->nombre . ' ' . $this->apellido1.(($this->apellido2)?' '.$this->apellido2:'');
    }
}

src/Form/ConductorType.php
<?php

namespace App\Form;

use App\Entity\Conductor;
use App\Utils\Globales;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Twig\Environment;

class ConductorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $globales = Globales::getGlobales();
        $builder
            ->add('nombre', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('apellido1', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('apellido2', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('nif', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('fecha_alta', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ])
        ;

        if ($options['include_fecha_baja']) {
            $builder->add('fecha_baja', null, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control'],
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Conductor::class,
            'include_fecha_baja' => false,
        ]);
    }
}

src/Controller/ConductorController.php
<?php

namespace App\Controller;

use App\Entity\Conductor;
use App\Entity\Viaje;
use App\Form\ConductorType;
use App\Repository\ConductorRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/conductor')]
final class ConductorController extends AbstractController
{
    #[Route(name: 'app_conductor_index', methods: ['GET'])]
    public function index(ConductorRepository $conductorRepository): Response
    {
        return $this->render('conductor/index.html.twig', [
            'conductors' => $conductorRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_conductor_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $conductor = new Conductor();
        $form = $this->createForm(ConductorType::class, $conductor, ['include_fecha_baja' => false]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($conductor);
            $entityManager->flush();

            return $this->redirectToRoute('app_conductor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('conductor/new.html.twig', [
            'conductor' => $conductor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_conductor_show', methods: ['GET'])]
    public function show(Conductor $conductor): Response
    {
        return $this->render('conductor/show.html.twig', [
            'conductor' => $conductor,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_conductor_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Conductor $conductor, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ConductorType::class, $conductor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_conductor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('conductor/edit.html.twig', [
            'conductor' => $conductor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_conductor_delete', methods: ['POST'])]
    public function delete(Request $request, Conductor $conductor, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$conductor->getId(), $request->getPayload()->getString('_token'))) {
            $numViajes=$entityManager->getRepository(Viaje::class)->getNumViajesByConductor($conductor->getId());
            if($numViajes>0){
                $this->addFlash('error', 'El conductor '.$conductor->getNombreCompleto().' no puede ser eliminado porque tiene '.$numViajes.' viajes asociados.');
                return $this->redirectToRoute('app_main_menu', [], Response::HTTP_SEE_OTHER);
            }
            $entityManager->remove($conductor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_conductor_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/conductor/_delete_form.html.twig
<form method="post" action="{{ path('app_conductor_delete', {'id': conductor.id}) }}" onsubmit="return confirm('{{ confirmar_borrado_conductor }}');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conductor.id) }}">
    <button class="{{ estilo_boton_eliminar }}">{{ eliminar }}</button>
</form>

templates/conductor/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="{{ estilo_boton_guardar }}">{{ button_label|default(guardar) }}</button>
{{ form_end(form) }}

templates/conductor/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_editar_conductor }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_editar_conductor }}</h3>
{% endblock %}

{% block contenido %}
    {{ include('conductor/_form.html.twig', {'button_label': actualizar }) }}

{% endblock%}

{% block acciones %}

    <a href="{{ path('app_conductor_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>

    {{ include('conductor/_delete_form.html.twig') }}
{% endblock %}

templates/conductor/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_listado_conductores }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_listado_conductores }}</h3>
{% endblock %}

{% block contenido %}
    <table class="{{ estilo_tabla }}">
        <thead>
            <tr>
                <th>{{ etiqueta_nombre_completo_conductor }}</th>
                <th>{{ etiqueta_nif_conductor }}</th>
                <th>{{ etiqueta_fecha_alta }}</th>
                <th>{{ etiqueta_fecha_baja }}</th>
                <th>{{ etiqueta_total_viajes }}</th>
                <th>{{ etiqueta_acciones }}</th>
            </tr>
        </thead>
        <tbody>
        {% for conductor in conductors %}
            <tr>
                <td>{{ conductor.nombreCompleto }}</td>
                <td>{{ conductor.nif }}</td>
                <td>{{ conductor.fechaAlta ? conductor.fechaAlta|date('d/m/Y') : '' }}</td>
                <td>{{ conductor.fechaBaja ? conductor.fechaBaja|date('d/m/Y') : '' }}</td>
                <td>{{ conductor.viajes|length }}</td>
                <td>
                    <a href="{{ path('app_conductor_show', {'id': conductor.id}) }}" class="{{ estilo_boton_detalle_incrustado }}">{{ ver_detalle }}</a>
                    <a href="{{ path('app_conductor_edit', {'id': conductor.id}) }}" class="{{ estilo_boton_editar_incrustado }}">{{ editar }}</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">{{ sin_resultados }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block acciones %}
    <a href="{{ path('app_conductor_new') }}" class="{{ estilo_boton_nuevo_elemento }}">{{ navega_nuevo_conductor }}</a>
{% endblock %}

templates/conductor/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_nuevo_conductor }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_nuevo_conductor }}</h3>
{% endblock %}

{% block contenido %}
    {% for msg in app.flashes('error') %}
        <div class="alert alert-danger">{{ msg }}</div>
    {% endfor %}
    {{ include('conductor/_form.html.twig') }}
{% endblock %}

{% block acciones %}
    <a href="{{ path('app_conductor_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>
{% endblock %}

templates/conductor/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ navega_detalle_conductor }}{% endblock %}

{% block cabecera %}
    <h3 class="{{ estilo_cabecera_pagina }}">{{ navega_detalle_conductor }}</h3>
{% endblock %}

{% block contenido %}
    <table class="{{ estilo_tabla }}">
        <tbody>
            <tr>
                <th>{{ etiqueta_nombre }}</th>
                <td>{{ conductor.nombre }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_apellido1 }}</th>
                <td>{{ conductor.apellido1 }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_apellido2 }}</th>
                <td>{{ conductor.apellido2 }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_nif_conductor }}</th>
                <td>{{ conductor.nif }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_total_viajes }}</th>
                <td>{{ conductor.viajes|length }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_fecha_alta }}</th>
                <td>{{ conductor.fechaAlta ? conductor.fechaAlta|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>{{ etiqueta_fecha_baja }}</th>
                <td>{{ conductor.fechaBaja ? conductor.fechaBaja|date('d/m/Y') : '' }}</td>
            </tr>
        </tbody>
    </table>

{% endblock %}

{% block acciones %}
    <a href="{{ path('app_conductor_index') }}" class="{{ estilo_boton_volver }}">{{ volver_al_listado }}</a>

    <a href="{{ path('app_conductor_edit', {'id': conductor.id}) }}" class="{{ estilo_boton_editar }}">{{ editar }}</a>

    {{ include('conductor/_delete_form.html.twig') }}
{% endblock %}